import React, { useState, useEffect } from 'react';
import { Room } from '../../types';
import { Button, Card, Icons } from '../../ui';
import { supabase } from '../../supabase';

export const RoomManagement = ({
    rooms,
    onUpdateRoom,
    onCreateRoom,
    onDeleteRoom,
    breakfastPrice,
    onUpdateBreakfastPrice
}: {
    rooms: Room[],
    onUpdateRoom: (room: Room) => void,
    onCreateRoom: (room: Room) => void,
    onDeleteRoom: (roomId: string) => void,
    breakfastPrice: number,
    onUpdateBreakfastPrice: (price: number) => void
}) => {
    const [editingRoom, setEditingRoom] = useState<Room | null>(null);
    const [isCreating, setIsCreating] = useState(false);
    const [isUploading, setIsUploading] = useState(false);
    const [statusMsg, setStatusMsg] = useState<{ type: 'success' | 'error', text: string } | null>(null);

    // Clear status message after 3 seconds
    useEffect(() => {
        if (statusMsg) {
            const timer = setTimeout(() => setStatusMsg(null), 3000);
            return () => clearTimeout(timer);
        }
    }, [statusMsg]);

    const handleEdit = (room: Room) => {
        setEditingRoom({ ...room });
        setIsCreating(false);
        setStatusMsg(null);
    };

    const handleCreate = () => {
        setEditingRoom({
            id: `room_${Date.now()}`,
            name: '',
            description: '',
            floorLocation: '樓下',
            maxGuests: 2,
            bedConfig: '',
            sizeSqm: 20,
            priceWeekday: 2000,
            priceHoliday: 2400,
            priceCny: 4000,
            price: 2000,
            images: [], // Default empty
            tags: [],
            amenities: []
        });
        setIsCreating(true);
        setStatusMsg(null);
    };

    const handleSave = async () => {
        if (!editingRoom) return;

        // Optimistic UI Update (or wait for reload)
        // Ideally we should move this logic to a service or context, but for MVP here is fine.

        try {
            // Upsert room type
            const { error } = await supabase
                .from('room_types')
                .upsert({
                    id: editingRoom.id,
                    name: editingRoom.name,
                    description: editingRoom.description,
                    floor_location: editingRoom.floorLocation,
                    max_guests: editingRoom.maxGuests,
                    bed_config: editingRoom.bedConfig || '', // Schema requires string
                    size_sqm: editingRoom.sizeSqm,
                    price_weekday: editingRoom.priceWeekday,
                    price_holiday: editingRoom.priceHoliday,
                    price_cny: editingRoom.priceCny,
                    amenities: editingRoom.amenities,
                    image_url: JSON.stringify(editingRoom.images) // Store array as JSON string
                });

            if (error) throw error;

            // Handle Physical Rooms (roomNumbers)
            // Strategy: Check existing, add new ones. 
            // For MVP: We only ADD new room numbers if they don't exist in `rooms` table for this type.
            // Removing room numbers usually requires checking bookings, so let's keep it simple: Add Only.
            if (editingRoom.roomNumbers && editingRoom.roomNumbers.length > 0) {
                for (const num of editingRoom.roomNumbers) {
                    await supabase.from('rooms').upsert({
                        room_number: num,
                        room_type_id: editingRoom.id,
                        is_active: true
                    });
                }
            }


            setStatusMsg({ type: 'success', text: '儲存成功！' });
            // Call parent update to refresh list in UI
            if (isCreating) {
                onCreateRoom({ ...editingRoom });
            } else {
                onUpdateRoom({ ...editingRoom });
            }

            // Trigger a re-fetch or rely on Realtime if implemented.
            // For now, since onUpdateRoom updates local state in App.tsx (or should), 
            // we can just close the modal.
            // However, App.tsx might need to re-fetch from Supabase to get the "true" state including IDs generated by DB?
            // Let's reload data silently if possible, or just trust the local update for now.
            // BETTER: Force a window reload ONLY if we really have to, but that logs us out.
            // Best approach: Just close modal. The `onUpdateRoom` in App.tsx currently updates local state.

            // Close modal after a short delay to show success message
            setTimeout(() => {
                setEditingRoom(null);
                setIsCreating(false);
            }, 1000);

        } catch (err) {
            console.error('Error saving room:', err);
            setStatusMsg({ type: 'error', text: '儲存失敗，請重試。' });
        }
    };

    const handleDelete = (roomId: string) => {
        if (window.confirm('確定要刪除此房型嗎？此動作無法復原。')) {
            onDeleteRoom(roomId);
        }
    };

    return (
        <div className="space-y-6 pb-32">

            {/* Breakfast Settings */}
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
                <h3 className="font-bold text-lg text-gray-900 mb-4">全局設定</h3>
                <div className="flex items-center gap-4">
                    <label className="text-sm font-bold text-gray-600">早餐加購價格 (人/晚)</label>
                    <div className="flex items-center gap-2">
                        <span className="text-gray-400">NT$</span>
                        <input
                            type="number"
                            value={breakfastPrice}
                            onChange={(e) => onUpdateBreakfastPrice(Number(e.target.value))}
                            className="border border-gray-300 rounded px-2 py-1 w-24 text-right font-bold text-gray-800"
                        />
                    </div>
                </div>
            </div>

            {/* Room List header */}
            <div className="flex items-center justify-between">
                <h2 className="font-bold text-xl text-gray-900">房型管理 ({rooms.length})</h2>
                <Button onClick={handleCreate} className="bg-black text-white px-4 py-2 text-sm rounded-lg hover:bg-gray-800">
                    + 新增房型
                </Button>
            </div>

            {/* Room List grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                {rooms.map(room => (
                    <Card key={room.id} className="p-3 flex flex-col sm:flex-row gap-3 h-full hover:shadow-md transition-shadow">
                        <div className="w-full h-32 sm:w-24 sm:h-24 bg-gray-100 rounded-lg overflow-hidden flex-shrink-0 relative group">
                            <img src={room.images[0]} alt={room.name} className="w-full h-full object-cover" />
                            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors" />
                        </div>
                        <div className="flex-1 min-w-0 flex flex-col justify-between">
                            <div className="flex justify-between items-start">
                                <div className="min-w-0 flex-1 mr-2">
                                    <h3 className="font-bold text-base text-gray-900 truncate">{room.name}</h3>
                                    <p className="text-xs text-gray-500 mt-0.5 truncate">{room.floorLocation} | {room.maxGuests}人 | {room.sizeSqm}坪</p>
                                    <p className="text-[10px] text-gray-400 truncate mt-0.5">{room.description}</p>
                                </div>
                                <div className="text-right flex-shrink-0">
                                    <span className="block font-bold text-green-600 text-sm">NT$ {room.priceWeekday.toLocaleString()}</span>
                                    <span className="text-[10px] text-gray-400">平日</span>
                                </div>
                            </div>

                            <div className="mt-3 flex justify-end gap-2 pt-2 border-t border-gray-50">
                                <Button
                                    variant="secondary"
                                    className="text-[10px] py-1 px-2 h-7 bg-gray-50 text-gray-600 hover:bg-gray-100"
                                    onClick={() => handleEdit(room)}
                                >
                                    <Icons.Settings className="w-3 h-3 mr-1 inline" /> 編輯
                                </Button>
                                <Button
                                    variant="secondary"
                                    className="text-[10px] py-1 px-2 h-7 bg-red-50 text-red-600 hover:bg-red-100 border-red-100"
                                    onClick={() => handleDelete(room.id)}
                                >
                                    刪除
                                </Button>
                            </div>
                        </div>
                    </Card>
                ))}
            </div>

            {/* Edit/Create Modal */}
            {editingRoom && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-white rounded-2xl w-full max-w-lg max-h-[90vh] overflow-y-auto shadow-2xl">
                        <div className="sticky top-0 bg-white border-b border-gray-100 p-4 flex justify-between items-center z-10">
                            <div className="flex items-center gap-3">
                                <h3 className="font-bold text-lg">{isCreating ? '新增房型' : '編輯房型'}</h3>
                                {statusMsg && (
                                    <span className={`text-xs px-2 py-1 rounded-full ${statusMsg.type === 'success' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                                        {statusMsg.text}
                                    </span>
                                )}
                            </div>
                            <button onClick={() => setEditingRoom(null)} className="text-gray-400 hover:text-gray-600">
                                ✕
                            </button>
                        </div>

                        <div className="p-6 space-y-4">
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-1">房型名稱</label>
                                <input
                                    type="text"
                                    value={editingRoom.name}
                                    onChange={e => setEditingRoom({ ...editingRoom, name: e.target.value })}
                                    className="w-full border border-gray-300 rounded-lg px-3 py-2"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-1">描述</label>
                                <textarea
                                    value={editingRoom.description}
                                    onChange={e => setEditingRoom({ ...editingRoom, description: e.target.value })}
                                    className="w-full border border-gray-300 rounded-lg px-3 py-2 h-20"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-1">房號管理 (用逗號隔開，例如: 201,202)</label>
                                <input
                                    type="text"
                                    value={editingRoom.roomNumbers?.join(',') || ''}
                                    onChange={e => setEditingRoom({ ...editingRoom, roomNumbers: e.target.value.split(',').map(s => s.trim()).filter(s => s !== '') })}
                                    className="w-full border border-gray-300 rounded-lg px-3 py-2 font-mono text-sm"
                                    placeholder="201, 202, 203"
                                />
                                <p className="text-xs text-gray-400 mt-1">這些房號將會顯示在實時看板供您管理</p>
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-1">最大人數</label>
                                <input
                                    type="number"
                                    value={editingRoom.maxGuests}
                                    onChange={e => setEditingRoom({ ...editingRoom, maxGuests: Number(e.target.value) })}
                                    className="w-full border border-gray-300 rounded-lg px-3 py-2"
                                />
                            </div>

                            <div className="grid grid-cols-3 gap-3 bg-gray-50 p-4 rounded-xl">
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 mb-1">平日價格</label>
                                    <input
                                        type="number"
                                        value={editingRoom.priceWeekday}
                                        onChange={e => setEditingRoom({ ...editingRoom, priceWeekday: Number(e.target.value), price: Number(e.target.value) })}
                                        className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 mb-1">假日價格</label>
                                    <input
                                        type="number"
                                        value={editingRoom.priceHoliday}
                                        onChange={e => setEditingRoom({ ...editingRoom, priceHoliday: Number(e.target.value) })}
                                        className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 mb-1">過年價格</label>
                                    <input
                                        type="number"
                                        value={editingRoom.priceCny}
                                        onChange={e => setEditingRoom({ ...editingRoom, priceCny: Number(e.target.value) })}
                                        className="w-full border border-gray-300 rounded px-2 py-1 text-sm"
                                    />
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">設施標籤</label>
                                <div className="flex flex-wrap gap-2">
                                    {['電視', '快煮壺', '沙發', '浴缸', '咖啡耳掛包', 'WIFI'].map(tag => {
                                        const isSelected = editingRoom.amenities?.includes(tag);
                                        return (
                                            <button
                                                key={tag}
                                                onClick={() => {
                                                    const current = editingRoom.amenities || [];
                                                    const newAmenities = isSelected
                                                        ? current.filter(t => t !== tag)
                                                        : [...current, tag];
                                                    setEditingRoom({ ...editingRoom, amenities: newAmenities });
                                                }}
                                                className={`px-3 py-1.5 rounded-full text-xs font-bold border transition-all ${isSelected
                                                    ? 'bg-black text-white border-black'
                                                    : 'bg-white text-gray-600 border-gray-200 hover:border-gray-300'
                                                    }`}
                                            >
                                                {isSelected ? '✓ ' : '+ '}{tag}
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">
                                    圖片 (最多 6 張) <span className="text-xs text-gray-400 font-normal ml-2">(建議尺寸 1200x900, 2MB 以內)</span>
                                </label>
                                <div className="grid grid-cols-3 gap-2">
                                    {/* Upload Input Logic */}
                                    <input
                                        type="file"
                                        id="room-image-upload"
                                        accept="image/*"
                                        className="hidden"
                                        disabled={isUploading}
                                        onChange={async (e) => {
                                            const file = e.target.files?.[0];
                                            if (!file) return;

                                            setIsUploading(true);
                                            setStatusMsg(null);

                                            try {
                                                const fileExt = file.name.split('.').pop();
                                                const fileName = `${Date.now()}.${fileExt}`;
                                                const filePath = `${fileName}`;

                                                const { error: uploadError } = await supabase.storage
                                                    .from('room-images')
                                                    .upload(filePath, file);

                                                if (uploadError) {
                                                    throw uploadError;
                                                }

                                                // Get Public URL
                                                const { data } = supabase.storage
                                                    .from('room-images')
                                                    .getPublicUrl(filePath);

                                                if (data) {
                                                    const newImages = [...editingRoom.images, data.publicUrl];
                                                    // Limit to 6
                                                    if (newImages.length > 6) {
                                                        setStatusMsg({ type: 'error', text: '最多只能上傳 6 張圖片' });
                                                        setIsUploading(false);
                                                        return;
                                                    }
                                                    setEditingRoom({ ...editingRoom, images: newImages });
                                                    setStatusMsg({ type: 'success', text: '圖片上傳完成' });
                                                }
                                            } catch (error) {
                                                console.error('Upload error:', error);
                                                setStatusMsg({ type: 'error', text: '上傳失敗，請檢查設定。' });
                                            } finally {
                                                setIsUploading(false);
                                            }
                                        }}
                                    />

                                    {[0, 1, 2, 3, 4, 5].map((index) => {
                                        const image = editingRoom.images[index];
                                        return (
                                            <div key={index} className="aspect-square rounded-lg border border-gray-200 overflow-hidden relative bg-gray-50">
                                                {image ? (
                                                    <>
                                                        <img src={image} alt={`Room ${index + 1}`} className="w-full h-full object-cover" />
                                                        <button
                                                            onClick={() => {
                                                                const newImages = [...editingRoom.images];
                                                                newImages.splice(index, 1);
                                                                setEditingRoom({ ...editingRoom, images: newImages });
                                                            }}
                                                            className="absolute top-1 right-1 bg-black/50 hover:bg-black/70 text-white rounded-full w-6 h-6 flex items-center justify-center text-xs backdrop-blur-sm transition-colors"
                                                        >
                                                            ✕
                                                        </button>
                                                    </>
                                                ) : (
                                                    <label
                                                        htmlFor="room-image-upload"
                                                        className={`w-full h-full flex flex-col items-center justify-center text-gray-400 transition-colors gap-1 ${isUploading ? 'cursor-not-allowed bg-gray-100' : 'cursor-pointer hover:bg-gray-100'}`}
                                                    >
                                                        {isUploading && index === editingRoom.images.length ? (
                                                            <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-gray-400"></div>
                                                        ) : (
                                                            <>
                                                                <span className="text-2xl">+</span>
                                                                <span className="text-[10px]">上傳圖片</span>
                                                            </>
                                                        )}
                                                    </label>
                                                )}
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        </div>

                        <div className="p-4 border-t border-gray-100 flex gap-3">
                            <Button
                                variant="secondary"
                                className="flex-1 bg-gray-100 text-gray-700 hover:bg-gray-200"
                                onClick={() => setEditingRoom(null)}
                            >
                                取消
                            </Button>
                            <Button
                                className="flex-1 bg-black text-white hover:bg-gray-800"
                                onClick={handleSave}
                            >
                                {isCreating ? '新增' : '儲存變更'}
                            </Button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};
